---
- name: "Uninstall unnecessary programs"
  import_tasks: "uninstall.yml"

- name: "Install programs"
  import_tasks: "install.yml"
  become: true

- name: "Set up UFW firewall"
  import_tasks: "ufw.yml"

- name: configure sshd
  import_tasks: "sshd_config.yml"

- name: confugure sudoers
  import_tasks: sudo_nopasswd.yml
  tags:
    - nopasswd

- name: configure wifi
  import_tasks: wifi.yml
  tags:
    - wifi

- name: configure cgroups
  import_tasks: cgroups.yml
  tags:
    - cgroups

- name: Change hostname
  import_tasks: hostname.yml
  tags:
    - hostname
