---
# Set up UFW firewall

- name: Configure UFW
  when: not disable_ufw | bool
  become: true
  block:

  - name: Make sure UFW is installed
    ansible.builtin.apt:
      name: ufw
      state: present

  - name: Set default incoming policy to deny
    community.general.ufw:
      direction: 'incoming'
      policy: 'deny'

  - name: Set default outgoing policy to allow
    community.general.ufw:
      direction: 'outgoing'
      policy: 'allow'

  - name: Allow ssh access
    community.general.ufw:
      rule: 'limit'  # limit incoming connections to 6connections/30sec
      port: 'ssh'
      proto: 'tcp'

  - name: Set logging
    community.general.ufw:
      logging: 'on'

  - name: Enable UWF
    community.general.ufw:
      state: 'enabled'
